-- JS Ass√≠ncrono: Promises e Fetch -- 

-- C√≥digo ass√≠ncrono --

**setTimeout( () => {}, tempoADefinir)**

-- Promises --

Se quisermos criar nossas pr√≥prias promises podemos usar o construtor *new Promise()* para criar uma nova promise. Esse construtor *recebe uma fun√ß√£o como par√¢metro* e essa *fun√ß√£o dever√° ter dois argumentos: a fun√ß√£o resolve e a fun√ß√£o reject*.

**new Promise( (resolve, reject) => {});**

Os par√¢metros *resolve* e **reject** ser√£o usados para definirmos qual o estado que promise ter√° quando for finalizada.

Quando a promise for *resolvida*, usamos a fun√ß√£o *resolve*;
Quando a promise for **rejeitada**, usamos a fun√ß√£o **reject**.


// fun√ß√£o que gera um n√∫mero aleat√≥rio
const generateRandomNumber = () => Math.round(Math.random() * 10);

// promise resolvida retornando o n√∫mero aleat√≥rio
const resolvedPromise = () =>
  new Promise((resolve, reject) => {
    setTimeout(() => {
      const randomNumber = generateRandomNumber();
      resolve(randomNumber);
    }, 1000);
  });

  Anota a√≠ üìù: Repare que podemos retornar qualquer valor usando a fun√ß√£o reject, mas geralmente √© uma boa pr√°tica retornar um objeto de erro.

  Recebendo o retorno da promise

  Utilizar " then para promise resolvida" e  " catch para promise com erro "
Sintaxe: 

function().then( (*response*) => {
    " retorno desejado "
}).catch( (**error**) => {
    " retorno desejado "
});

O response √© o retorno da fun√ßao *resolve* e o error √© o retorno da fun√ßao **reject**.

Caso seja necess√°rio executar algum c√≥digo ap√≥s o retorno da promise, independentemente se ela foi resolvida ou rejeitada, podemos usar o m√©todo finally. Esse m√©todo recebe como par√¢metro uma fun√ß√£o, que n√£o recebe nenhum argumento.